mode = "dark"

accent = "#b8557d"
selection = "#b8557d"
muted = "#434353"

background = "#131313"
dark_background = "#0e0e0e"
darker_background = "#0a0a0a"
lighter_background = "#1e1e2d"

foreground = "#f5f5d0"
dark_foreground = "#a1a2a7"
light_foreground = "#e0e0e0"
bright_foreground = "#f5f5d0"

selection_foreground = "#13131D"

red = "#EA90A8"
yellow = "#D18BA2"
orange = "#e3aebf"
green = "#a6b2c7"
cyan = "#919ab7"
blue = "#7c7ca8"
magenta = "#9f859f"

bright_red = "#f6bfce"
bright_yellow = "#e3aebf"
bright_green = "#d1d9e4"
bright_cyan = "#d2d7e3"
bright_blue = "#bcbcd4"
bright_magenta = "#bfadbf"

# Hyprland border colors, also picked up by the Omarchy shell theme
hyprland_active_border = "rgba(EA90A866)"
hyprland_inactive_border = "rgba(43435360)"
