# Ghostty Terminal Configuration

# Window & Layout
window-padding-x = 15
window-padding-y = 15

# Background & Opacity
background-opacity = 0.4
background = #131313

# Text Colors
foreground = #f5f5d0

# Cursor
cursor-color = #EA90A8
cursor-text = #13131D

# Selection
selection-background = #ff7eb6
selection-foreground = #13131D

# Color Palette
palette = 0=#13131D
palette = 1=#EA90A8
palette = 2=#a6b2c7
palette = 3=#D18BA2
palette = 4=#7c7ca8
palette = 5=#9f859f
palette = 6=#919ab7
palette = 7=#e0e0e0

# Bright colors
palette = 8=#434353
palette = 9=#f6bfce
palette = 10=#d1d9e4
palette = 11=#e3aebf
palette = 12=#bcbcd4
palette = 13=#bfadbf
palette = 14=#d2d7e3
palette = 15=#ffffff

# Font Size 
font-size = 12
