return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      float = { transparent = true },
      color_overrides = {
        mocha = {
          base = "#1a1a2e",
          mantle = "#1a1a2e",
          crust = "#13131D",
          flamingo = "#f2aebf",
          pink = "#EA90A8",
          mauve = "#D18BA2",
          red = "#EA90A8",
          maroon = "#D18BA2",
          peach = "#e3aebf",
          yellow = "#D18BA2",
          green = "#a6b2c7",
          teal = "#919ab7",
          sky = "#bcbcd4",
          sapphire = "#7c7ca8",
          blue = "#7c7ca8",
          lavender = "#9f859f",
          text = "#f5f5d0",
          subtext1 = "#a1a2a7",
          subtext0 = "#919ab7",
          overlay2 = "#bcbcd4",
          overlay1 = "#a6b2c7",
          overlay0 = "#7c7ca8",
          surface2 = "#434353",
          surface1 = "#2a2a3d",
          surface0 = "#1e1e2d",
        },
      },
      custom_highlights = function(colors)
        return {
          LineNr = { fg = "#f5f5d0" },
          NormalFloat = { bg = "NONE", fg = colors.text },
          FloatBorder = { bg = "NONE", fg = colors.pink },
          FloatTitle = { bg = "NONE", fg = colors.pink },
          TelescopeNormal = { bg = "NONE", fg = colors.text },
          TelescopeBorder = { bg = "NONE", fg = colors.pink },
          TelescopePromptNormal = { bg = "NONE", fg = colors.text },
          TelescopePromptBorder = { bg = "NONE", fg = colors.pink },
          TelescopePromptTitle = { bg = "NONE", fg = colors.pink },
          TelescopePreviewTitle = { bg = "NONE", fg = colors.pink },
          TelescopeResultsTitle = { bg = "NONE", fg = colors.pink },
          WhichKey = { bg = "NONE", fg = colors.pink },
          WhichKeyGroup = { bg = "NONE", fg = colors.blue },
          WhichKeyDesc = { bg = "NONE", fg = colors.text },
          WhichKeyBorder = { bg = "NONE", fg = colors.pink },
          LazyNormal = { bg = "NONE", fg = colors.text },
          LazyBorder = { bg = "NONE", fg = colors.pink },
          MasonNormal = { bg = "NONE", fg = colors.text },
          MasonBorder = { bg = "NONE", fg = colors.pink },
          NeoTreeNormal = { bg = "NONE", fg = colors.text },
          NeoTreeNormalNC = { bg = "NONE", fg = colors.subtext0 },
          NeoTreeFloatBorder = { bg = "NONE", fg = colors.pink },
          NeoTreeDirectoryIcon = { fg = colors.pink },
          NeoTreeDirectoryName = { fg = colors.text },
          NeoTreeFileName = { fg = colors.text },
          NeoTreeGitModified = { fg = colors.pink },
          NeoTreeGitAdded = { fg = colors.green },
          NeoTreeGitDeleted = { fg = colors.mauve },
          CmpItemAbbr = { fg = colors.text },
          CmpItemAbbrMatch = { fg = colors.pink, bold = true },
          CmpItemAbbrMatchFuzzy = { fg = colors.pink, bold = true },
          DiagnosticError = { fg = colors.pink },
          DiagnosticWarn = { fg = colors.peach },
          DiagnosticInfo = { fg = colors.blue },
          DiagnosticHint = { fg = colors.green },
          Function = { fg = colors.pink },
          Keyword = { fg = colors.mauve },
          String = { fg = colors.green },
          Number = { fg = colors.peach },
          Boolean = { fg = colors.pink, bold = true },
          Type = { fg = colors.blue },
          Comment = { fg = colors.surface2, italic = true },
          Constant = { fg = colors.pink },
          Operator = { fg = colors.mauve },
          Statement = { fg = colors.mauve },
          Identifier = { fg = colors.text },
          PreProc = { fg = colors.lavender },
        }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "catppuccin" },
  },
}
